-- Q1: Total number of rentals in Sakila (COUNT)
SELECT COUNT(*) AS total_rentals
FROM rental;

-- Q2: Average rental duration (AVG) of movies
SELECT AVG(rental_duration) AS avg_rental_duration
FROM film;

-- Q3: Customer names in uppercase (UPPER)
SELECT UPPER(first_name) AS first_name_upper, UPPER(last_name) AS last_name_upper
FROM customer;

-- Q4: Extract month from rental_date (MONTH)
SELECT rental_id, MONTH(rental_date) AS rental_month
FROM rental;

-- Q5: Count of rentals per customer (GROUP BY)
SELECT customer_id, COUNT(*) AS rental_count
FROM rental
GROUP BY customer_id;

-- Q6: Total revenue generated by each store (SUM, GROUP BY)
SELECT store_id, SUM(amount) AS total_revenue
FROM payment 
GROUP BY store_id;

-- Q7: Total number of rentals per movie category (JOIN + COUNT)
SELECT c.name AS category_name, COUNT(*) AS rentals_count
FROM category AS c
JOIN film_category AS fc ON c.category_id = fc.category_id
JOIN inventory AS i ON fc.film_id = i.film_id
JOIN rental AS r ON i.inventory_id = r.inventory_id
GROUP BY c.category_id, c.name;

-- Q8: Average rental rate of movies in each language (JOIN + AVG)
SELECT l.name AS language, AVG(f.rental_rate) AS avg_rate
FROM language AS l
JOIN film AS f ON l.language_id = f.language_id
GROUP BY l.language_id, l.name;
